x-app-env:
  - 'NEXTAUTH_URL=${SERVICE_URL_LANGFUSE}'
  - 'DATABASE_URL=postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@${POSTGRES_HOST}:5432/${POSTGRES_DB:-langfuse-db}'
  - 'SALT=${SERVICE_PASSWORD_SALT}'
  - 'ENCRYPTION_KEY=${ENCRYPTION_KEY}'
  - 'TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-false}'
  - 'LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}'
  - 'CLICKHOUSE_MIGRATION_URL=clickhouse://clickhouse:9000'
  - 'CLICKHOUSE_URL=http://clickhouse:8123'
  - 'CLICKHOUSE_USER=${SERVICE_USER_CLICKHOUSE}'
  - 'CLICKHOUSE_PASSWORD=${SERVICE_PASSWORD_CLICKHOUSE}'
  - CLICKHOUSE_CLUSTER_ENABLED=false
  - 'LANGFUSE_USE_AZURE_BLOB=${LANGFUSE_USE_AZURE_BLOB:-false}'
  - 'LANGFUSE_S3_EVENT_UPLOAD_BUCKET=${LANGFUSE_S3_EVENT_UPLOAD_BUCKET:-langfuse}'
  - 'LANGFUSE_S3_EVENT_UPLOAD_REGION=${LANGFUSE_S3_EVENT_UPLOAD_REGION:-auto}'
  - 'LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=${SERVICE_USER_MINIO}'
  - 'LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=${SERVICE_PASSWORD_MINIO}'
  - 'LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=http://minio:9000'
  - 'LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE=${LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE:-true}'
  - 'LANGFUSE_S3_EVENT_UPLOAD_PREFIX=${LANGFUSE_S3_EVENT_UPLOAD_PREFIX:-events/}'
  - 'LANGFUSE_S3_MEDIA_UPLOAD_BUCKET=${LANGFUSE_S3_MEDIA_UPLOAD_BUCKET:-langfuse}'
  - 'LANGFUSE_S3_MEDIA_UPLOAD_REGION=${LANGFUSE_S3_MEDIA_UPLOAD_REGION:-auto}'
  - 'LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=${SERVICE_USER_MINIO}'
  - 'LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=${SERVICE_PASSWORD_MINIO}'
  - 'LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT=http://minio:9000'
  - 'LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE=${LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE:-true}'
  - 'LANGFUSE_S3_MEDIA_UPLOAD_PREFIX=${LANGFUSE_S3_MEDIA_UPLOAD_PREFIX:-media/}'
  - 'LANGFUSE_S3_BATCH_EXPORT_ENABLED=${LANGFUSE_S3_BATCH_EXPORT_ENABLED:-false}'
  - 'LANGFUSE_S3_BATCH_EXPORT_BUCKET=${LANGFUSE_S3_BATCH_EXPORT_BUCKET:-langfuse}'
  - 'LANGFUSE_S3_BATCH_EXPORT_PREFIX=${LANGFUSE_S3_BATCH_EXPORT_PREFIX:-exports/}'
  - 'LANGFUSE_S3_BATCH_EXPORT_REGION=${LANGFUSE_S3_BATCH_EXPORT_REGION:-auto}'
  - 'LANGFUSE_S3_BATCH_EXPORT_ENDPOINT=http://minio:9000'
  - 'LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT=${LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT}'
  - 'LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID=${SERVICE_USER_MINIO}'
  - 'LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=${SERVICE_PASSWORD_MINIO}'
  - 'LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE=${LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE:-true}'
  - 'LANGFUSE_INGESTION_QUEUE_DELAY_MS=${LANGFUSE_INGESTION_QUEUE_DELAY_MS:-1}'
  - 'LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS=${LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS:-1000}'
  - 'REDIS_HOST=${REDIS_HOST}'
  - REDIS_PORT=6379
  - 'REDIS_AUTH=${SERVICE_PASSWORD_REDIS}'
  - 'EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS:-admin@example.com}'
  - 'SMTP_CONNECTION_URL=${SMTP_CONNECTION_URL:-}'
  - 'NEXTAUTH_SECRET=${SERVICE_BASE64_NEXTAUTHSECRET}'
  - 'AUTH_DISABLE_SIGNUP=${AUTH_DISABLE_SIGNUP:-true}'
  - 'HOSTNAME=${HOSTNAME:-0.0.0.0}'
  - 'LANGFUSE_INIT_ORG_ID=${LANGFUSE_INIT_ORG_ID:-my-org}'
  - 'LANGFUSE_INIT_ORG_NAME=${LANGFUSE_INIT_ORG_NAME:-My Org}'
  - 'LANGFUSE_INIT_PROJECT_ID=${LANGFUSE_INIT_PROJECT_ID:-my-project}'
  - 'LANGFUSE_INIT_PROJECT_NAME=${LANGFUSE_INIT_PROJECT_NAME:-My Project}'
  - 'LANGFUSE_INIT_USER_EMAIL=${LANGFUSE_INIT_USER_EMAIL:-admin@example.com}'
  - 'LANGFUSE_INIT_USER_NAME=${SERVICE_USER_LANGFUSE}'
  - 'LANGFUSE_INIT_USER_PASSWORD=${SERVICE_PASSWORD_LANGFUSE}'
services:
  langfuse:
    image: 'langfuse/langfuse:3'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      0: 'NEXTAUTH_URL=${SERVICE_URL_LANGFUSE}'
      1: 'DATABASE_URL=postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@${POSTGRES_HOST}:5432/${POSTGRES_DB:-langfuse-db}'
      2: 'SALT=${SERVICE_PASSWORD_SALT}'
      3: 'ENCRYPTION_KEY=${ENCRYPTION_KEY}'
      4: 'TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-false}'
      5: 'LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}'
      6: 'CLICKHOUSE_MIGRATION_URL=clickhouse://clickhouse:9000'
      7: 'CLICKHOUSE_URL=http://clickhouse:8123'
      8: 'CLICKHOUSE_USER=${SERVICE_USER_CLICKHOUSE}'
      9: 'CLICKHOUSE_PASSWORD=${SERVICE_PASSWORD_CLICKHOUSE}'
      10: CLICKHOUSE_CLUSTER_ENABLED=false
      11: 'LANGFUSE_USE_AZURE_BLOB=${LANGFUSE_USE_AZURE_BLOB:-false}'
      12: 'LANGFUSE_S3_EVENT_UPLOAD_BUCKET=${LANGFUSE_S3_EVENT_UPLOAD_BUCKET:-langfuse}'
      13: 'LANGFUSE_S3_EVENT_UPLOAD_REGION=${LANGFUSE_S3_EVENT_UPLOAD_REGION:-auto}'
      14: 'LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=${LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID}'
      15: 'LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=${LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY}'
      16: 'LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=${LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT}'
      17: 'LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE=${LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE:-true}'
      18: 'LANGFUSE_S3_EVENT_UPLOAD_PREFIX=${LANGFUSE_S3_EVENT_UPLOAD_PREFIX:-events/}'
      19: 'LANGFUSE_S3_MEDIA_UPLOAD_BUCKET=${LANGFUSE_S3_MEDIA_UPLOAD_BUCKET:-langfuse}'
      20: 'LANGFUSE_S3_MEDIA_UPLOAD_REGION=${LANGFUSE_S3_MEDIA_UPLOAD_REGION:-auto}'
      21: 'LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=${LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID}'
      22: 'LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=${LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY}'
      23: 'LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT=${LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT}'
      24: 'LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE=${LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE:-true}'
      25: 'LANGFUSE_S3_MEDIA_UPLOAD_PREFIX=${LANGFUSE_S3_MEDIA_UPLOAD_PREFIX:-media/}'
      26: 'LANGFUSE_S3_BATCH_EXPORT_ENABLED=${LANGFUSE_S3_BATCH_EXPORT_ENABLED:-false}'
      27: 'LANGFUSE_S3_BATCH_EXPORT_BUCKET=${LANGFUSE_S3_BATCH_EXPORT_BUCKET:-langfuse}'
      28: 'LANGFUSE_S3_BATCH_EXPORT_PREFIX=${LANGFUSE_S3_BATCH_EXPORT_PREFIX:-exports/}'
      29: 'LANGFUSE_S3_BATCH_EXPORT_REGION=${LANGFUSE_S3_BATCH_EXPORT_REGION:-auto}'
      30: 'LANGFUSE_S3_BATCH_EXPORT_ENDPOINT=${LANGFUSE_S3_BATCH_EXPORT_ENDPOINT}'
      31: 'LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT=${LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT}'
      32: 'LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID=${LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID}'
      33: 'LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=${LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY}'
      34: 'LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE=${LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE:-true}'
      35: 'LANGFUSE_INGESTION_QUEUE_DELAY_MS=${LANGFUSE_INGESTION_QUEUE_DELAY_MS:-1}'
      36: 'LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS=${LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS:-1000}'
      37: 'REDIS_HOST=${REDIS_HOST}'
      38: REDIS_PORT=6379
      39: 'REDIS_AUTH=${SERVICE_PASSWORD_REDIS}'
      40: 'EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS:-admin@example.com}'
      41: 'SMTP_CONNECTION_URL=${SMTP_CONNECTION_URL:-}'
      42: 'NEXTAUTH_SECRET=${SERVICE_BASE64_NEXTAUTHSECRET}'
      43: 'AUTH_DISABLE_SIGNUP=${AUTH_DISABLE_SIGNUP:-true}'
      44: 'HOSTNAME=${HOSTNAME:-0.0.0.0}'
      45: 'LANGFUSE_INIT_ORG_ID=${LANGFUSE_INIT_ORG_ID:-my-org}'
      46: 'LANGFUSE_INIT_ORG_NAME=${LANGFUSE_INIT_ORG_NAME:-My Org}'
      47: 'LANGFUSE_INIT_PROJECT_ID=${LANGFUSE_INIT_PROJECT_ID:-my-project}'
      48: 'LANGFUSE_INIT_PROJECT_NAME=${LANGFUSE_INIT_PROJECT_NAME:-My Project}'
      49: 'LANGFUSE_INIT_USER_EMAIL=${LANGFUSE_INIT_USER_EMAIL:-admin@example.com}'
      50: 'LANGFUSE_INIT_USER_NAME=${SERVICE_USER_LANGFUSE}'
      51: 'LANGFUSE_INIT_USER_PASSWORD=${SERVICE_PASSWORD_LANGFUSE}'
      SERVICE_URL_LANGFUSE_3000: '${SERVICE_URL_LANGFUSE_3000}'
    healthcheck:
      test:
        - CMD
        - wget
        - '-q'
        - '--spider'
        - 'http://127.0.0.1:3000/api/public/health'
      interval: 5s
      timeout: 5s
      retries: 3
  langfuse-worker:
    image: 'langfuse/langfuse-worker:3'
    environment:
      - 'NEXTAUTH_URL=${SERVICE_URL_LANGFUSE}'
      - 'DATABASE_URL=postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@${POSTGRES_HOST}:5432/${POSTGRES_DB:-langfuse-db}'
      - 'SALT=${SERVICE_PASSWORD_SALT}'
      - 'ENCRYPTION_KEY=${ENCRYPTION_KEY}'
      - 'TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-false}'
      - 'LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}'
      - 'CLICKHOUSE_MIGRATION_URL=clickhouse://clickhouse:9000'
      - 'CLICKHOUSE_URL=http://clickhouse:8123'
      - 'CLICKHOUSE_USER=${SERVICE_USER_CLICKHOUSE}'
      - 'CLICKHOUSE_PASSWORD=${SERVICE_PASSWORD_CLICKHOUSE}'
      - CLICKHOUSE_CLUSTER_ENABLED=false
      - 'LANGFUSE_USE_AZURE_BLOB=${LANGFUSE_USE_AZURE_BLOB:-false}'
      - 'LANGFUSE_S3_EVENT_UPLOAD_BUCKET=${LANGFUSE_S3_EVENT_UPLOAD_BUCKET:-langfuse}'
      - 'LANGFUSE_S3_EVENT_UPLOAD_REGION=${LANGFUSE_S3_EVENT_UPLOAD_REGION:-auto}'
      - 'LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=${LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID}'
      - 'LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=${LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY}'
      - 'LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=${LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT}'
      - 'LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE=${LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE:-true}'
      - 'LANGFUSE_S3_EVENT_UPLOAD_PREFIX=${LANGFUSE_S3_EVENT_UPLOAD_PREFIX:-events/}'
      - 'LANGFUSE_S3_MEDIA_UPLOAD_BUCKET=${LANGFUSE_S3_MEDIA_UPLOAD_BUCKET:-langfuse}'
      - 'LANGFUSE_S3_MEDIA_UPLOAD_REGION=${LANGFUSE_S3_MEDIA_UPLOAD_REGION:-auto}'
      - 'LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=${LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID}'
      - 'LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=${LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY}'
      - 'LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT=${LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT}'
      - 'LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE=${LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE:-true}'
      - 'LANGFUSE_S3_MEDIA_UPLOAD_PREFIX=${LANGFUSE_S3_MEDIA_UPLOAD_PREFIX:-media/}'
      - 'LANGFUSE_S3_BATCH_EXPORT_ENABLED=${LANGFUSE_S3_BATCH_EXPORT_ENABLED:-false}'
      - 'LANGFUSE_S3_BATCH_EXPORT_BUCKET=${LANGFUSE_S3_BATCH_EXPORT_BUCKET:-langfuse}'
      - 'LANGFUSE_S3_BATCH_EXPORT_PREFIX=${LANGFUSE_S3_BATCH_EXPORT_PREFIX:-exports/}'
      - 'LANGFUSE_S3_BATCH_EXPORT_REGION=${LANGFUSE_S3_BATCH_EXPORT_REGION:-auto}'
      - 'LANGFUSE_S3_BATCH_EXPORT_ENDPOINT=${LANGFUSE_S3_BATCH_EXPORT_ENDPOINT}'
      - 'LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT=${LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT}'
      - 'LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID=${LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID}'
      - 'LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=${LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY}'
      - 'LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE=${LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE:-true}'
      - 'LANGFUSE_INGESTION_QUEUE_DELAY_MS=${LANGFUSE_INGESTION_QUEUE_DELAY_MS:-1}'
      - 'LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS=${LANGFUSE_INGESTION_CLICKHOUSE_WRITE_INTERVAL_MS:-1000}'
      - 'REDIS_HOST=${REDIS_HOST}'
      - REDIS_PORT=6379
      - 'REDIS_AUTH=${SERVICE_PASSWORD_REDIS}'
      - 'EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS:-admin@example.com}'
      - 'SMTP_CONNECTION_URL=${SMTP_CONNECTION_URL:-}'
      - 'NEXTAUTH_SECRET=${SERVICE_BASE64_NEXTAUTHSECRET}'
      - 'AUTH_DISABLE_SIGNUP=${AUTH_DISABLE_SIGNUP:-true}'
      - 'HOSTNAME=${HOSTNAME:-0.0.0.0}'
      - 'LANGFUSE_INIT_ORG_ID=${LANGFUSE_INIT_ORG_ID:-my-org}'
      - 'LANGFUSE_INIT_ORG_NAME=${LANGFUSE_INIT_ORG_NAME:-My Org}'
      - 'LANGFUSE_INIT_PROJECT_ID=${LANGFUSE_INIT_PROJECT_ID:-my-project}'
      - 'LANGFUSE_INIT_PROJECT_NAME=${LANGFUSE_INIT_PROJECT_NAME:-My Project}'
      - 'LANGFUSE_INIT_USER_EMAIL=${LANGFUSE_INIT_USER_EMAIL:-admin@example.com}'
      - 'LANGFUSE_INIT_USER_NAME=${SERVICE_USER_LANGFUSE}'
      - 'LANGFUSE_INIT_USER_PASSWORD=${SERVICE_PASSWORD_LANGFUSE}'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - wget
        - '-q'
        - '--spider'
        - 'http://127.0.0.1:3030/api/health'
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
  postgres:
    image: 'postgres:17-alpine'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB:-langfuse-db}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
    volumes:
      - 'langfuse_postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: 'redis:8'
    command:
      - sh
      - '-c'
      - 'redis-server --requirepass "$SERVICE_PASSWORD_REDIS"'
    environment:
      - 'REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}'
    volumes:
      - 'langfuse_redis_data:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - '-a'
        - $SERVICE_PASSWORD_REDIS
        - PING
      interval: 3s
      timeout: 10s
      retries: 10
  minio:
    image: 'minio/minio:latest'
    command: 'server /data --console-address ":9001"'
    environment:
      - 'MINIO_ROOT_USER=${SERVICE_USER_MINIO:-minio}'
      - 'MINIO_ROOT_PASSWORD=${SERVICE_PASSWORD_MINIO:-miniosecret}'
    volumes:
      - 'langfuse_minio_data:/data'
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      interval: 5s
      timeout: 5s
      retries: 10
  minio-init:
    image: 'minio/mc:latest'
    restart: 'no'
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: "/bin/sh -c \" mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}; mc mb myminio/langfuse --ignore-existing; exit 0; \"\n"
    environment:
      - 'MINIO_ROOT_USER=${SERVICE_USER_MINIO:-minio}'
      - 'MINIO_ROOT_PASSWORD=${SERVICE_PASSWORD_MINIO:-miniosecret}'
  clickhouse:
    image: 'clickhouse/clickhouse-server:latest'
    user: '101:101'
    environment:
      - 'CLICKHOUSE_DB=${CLICKHOUSE_DB:-default}'
      - 'CLICKHOUSE_USER=${SERVICE_USER_CLICKHOUSE}'
      - 'CLICKHOUSE_PASSWORD=${SERVICE_PASSWORD_CLICKHOUSE}'
    volumes:
      - 'langfuse_clickhouse_data:/var/lib/clickhouse'
      - 'langfuse_clickhouse_logs:/var/log/clickhouse-server'
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1'
      interval: 5s
      timeout: 5s
      retries: 10
