services:
  postgres:
    image: postgres:15
    container_name: las-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: las
      POSTGRES_PASSWORD: las
      POSTGRES_DB: las
    ports:
      - "5432:5432"
    volumes:
      - las-postgres-data:/var/lib/postgresql/data

volumes:
  las-postgres-data:
